// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: grpc/common/marmot_common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatementType represents the type of SQL statement on the wire.
// This is the ONLY definition - used by all gRPC messages.
type StatementType int32

const (
	StatementType_INSERT          StatementType = 0
	StatementType_UPDATE          StatementType = 1
	StatementType_DELETE          StatementType = 2
	StatementType_REPLACE         StatementType = 3
	StatementType_DDL             StatementType = 4
	StatementType_CREATE_DATABASE StatementType = 5
	StatementType_DROP_DATABASE   StatementType = 6
)

// Enum value maps for StatementType.
var (
	StatementType_name = map[int32]string{
		0: "INSERT",
		1: "UPDATE",
		2: "DELETE",
		3: "REPLACE",
		4: "DDL",
		5: "CREATE_DATABASE",
		6: "DROP_DATABASE",
	}
	StatementType_value = map[string]int32{
		"INSERT":          0,
		"UPDATE":          1,
		"DELETE":          2,
		"REPLACE":         3,
		"DDL":             4,
		"CREATE_DATABASE": 5,
		"DROP_DATABASE":   6,
	}
)

func (x StatementType) Enum() *StatementType {
	p := new(StatementType)
	*p = x
	return p
}

func (x StatementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatementType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_common_marmot_common_proto_enumTypes[0].Descriptor()
}

func (StatementType) Type() protoreflect.EnumType {
	return &file_grpc_common_marmot_common_proto_enumTypes[0]
}

func (x StatementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatementType.Descriptor instead.
func (StatementType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_common_marmot_common_proto_rawDescGZIP(), []int{0}
}

var File_grpc_common_marmot_common_proto protoreflect.FileDescriptor

const file_grpc_common_marmot_common_proto_rawDesc = "" +
	"\n" +
	"\x1fgrpc/common/marmot_common.proto\x12\rmarmot.common*q\n" +
	"\rStatementType\x12\n" +
	"\n" +
	"\x06INSERT\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\x12\v\n" +
	"\aREPLACE\x10\x03\x12\a\n" +
	"\x03DDL\x10\x04\x12\x13\n" +
	"\x0fCREATE_DATABASE\x10\x05\x12\x11\n" +
	"\rDROP_DATABASE\x10\x06B'Z%github.com/maxpert/marmot/grpc/commonb\x06proto3"

var (
	file_grpc_common_marmot_common_proto_rawDescOnce sync.Once
	file_grpc_common_marmot_common_proto_rawDescData []byte
)

func file_grpc_common_marmot_common_proto_rawDescGZIP() []byte {
	file_grpc_common_marmot_common_proto_rawDescOnce.Do(func() {
		file_grpc_common_marmot_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_common_marmot_common_proto_rawDesc), len(file_grpc_common_marmot_common_proto_rawDesc)))
	})
	return file_grpc_common_marmot_common_proto_rawDescData
}

var file_grpc_common_marmot_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_common_marmot_common_proto_goTypes = []any{
	(StatementType)(0), // 0: marmot.common.StatementType
}
var file_grpc_common_marmot_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_common_marmot_common_proto_init() }
func file_grpc_common_marmot_common_proto_init() {
	if File_grpc_common_marmot_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_common_marmot_common_proto_rawDesc), len(file_grpc_common_marmot_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_common_marmot_common_proto_goTypes,
		DependencyIndexes: file_grpc_common_marmot_common_proto_depIdxs,
		EnumInfos:         file_grpc_common_marmot_common_proto_enumTypes,
	}.Build()
	File_grpc_common_marmot_common_proto = out.File
	file_grpc_common_marmot_common_proto_goTypes = nil
	file_grpc_common_marmot_common_proto_depIdxs = nil
}
