// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: grpc/marmot.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarmotService_Gossip_FullMethodName               = "/marmot.v2.MarmotService/Gossip"
	MarmotService_Join_FullMethodName                 = "/marmot.v2.MarmotService/Join"
	MarmotService_Ping_FullMethodName                 = "/marmot.v2.MarmotService/Ping"
	MarmotService_ReplicateTransaction_FullMethodName = "/marmot.v2.MarmotService/ReplicateTransaction"
	MarmotService_Read_FullMethodName                 = "/marmot.v2.MarmotService/Read"
	MarmotService_StreamChanges_FullMethodName        = "/marmot.v2.MarmotService/StreamChanges"
	MarmotService_GetReplicationState_FullMethodName  = "/marmot.v2.MarmotService/GetReplicationState"
	MarmotService_GetSnapshotInfo_FullMethodName      = "/marmot.v2.MarmotService/GetSnapshotInfo"
	MarmotService_StreamSnapshot_FullMethodName       = "/marmot.v2.MarmotService/StreamSnapshot"
	MarmotService_GetLatestTxnIDs_FullMethodName      = "/marmot.v2.MarmotService/GetLatestTxnIDs"
	MarmotService_GetClusterNodes_FullMethodName      = "/marmot.v2.MarmotService/GetClusterNodes"
	MarmotService_ForwardQuery_FullMethodName         = "/marmot.v2.MarmotService/ForwardQuery"
	MarmotService_ForwardLoadData_FullMethodName      = "/marmot.v2.MarmotService/ForwardLoadData"
	MarmotService_GetLoadDataChunk_FullMethodName     = "/marmot.v2.MarmotService/GetLoadDataChunk"
	MarmotService_TransactionStream_FullMethodName    = "/marmot.v2.MarmotService/TransactionStream"
)

// MarmotServiceClient is the client API for MarmotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Single gRPC service for all peer communication
type MarmotServiceClient interface {
	// ===== GOSSIP PROTOCOL =====
	// Periodic gossip messages (SWIM-style)
	Gossip(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*GossipResponse, error)
	// Join cluster
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	// Heartbeat/health check
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// ===== REPLICATION =====
	// Replicate transaction (quorum writes)
	ReplicateTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	// Quorum read
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// Streaming changes (for catch-up)
	StreamChanges(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeEvent], error)
	// Get replication state (for anti-entropy)
	GetReplicationState(ctx context.Context, in *ReplicationStateRequest, opts ...grpc.CallOption) (*ReplicationStateResponse, error)
	// ===== SNAPSHOT TRANSFER =====
	// Get snapshot metadata
	GetSnapshotInfo(ctx context.Context, in *SnapshotInfoRequest, opts ...grpc.CallOption) (*SnapshotInfoResponse, error)
	// Stream snapshot chunks
	StreamSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error)
	// Get latest transaction IDs per database (for delta sync detection)
	GetLatestTxnIDs(ctx context.Context, in *LatestTxnIDsRequest, opts ...grpc.CallOption) (*LatestTxnIDsResponse, error)
	// GetClusterNodes returns cluster membership for readonly replicas.
	// Read-only - does not modify cluster state.
	GetClusterNodes(ctx context.Context, in *GetClusterNodesRequest, opts ...grpc.CallOption) (*GetClusterNodesResponse, error)
	// Forward write query from read-only replica to leader
	ForwardQuery(ctx context.Context, in *ForwardQueryRequest, opts ...grpc.CallOption) (*ForwardQueryResponse, error)
	// Forward LOAD DATA LOCAL INFILE payload from read-only replica to leader.
	ForwardLoadData(ctx context.Context, in *ForwardLoadDataRequest, opts ...grpc.CallOption) (*ForwardQueryResponse, error)
	// Fetch staged LOAD DATA payload chunk by chunk.
	GetLoadDataChunk(ctx context.Context, in *LoadDataChunkRequest, opts ...grpc.CallOption) (*LoadDataChunkResponse, error)
	// ===== CDC STREAMING =====
	// Client-streaming RPC for large CDC payloads (≥128KB)
	// Sends TransactionChunks followed by TransactionCommit
	TransactionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TransactionStreamMessage, TransactionResponse], error)
}

type marmotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarmotServiceClient(cc grpc.ClientConnInterface) MarmotServiceClient {
	return &marmotServiceClient{cc}
}

func (c *marmotServiceClient) Gossip(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*GossipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipResponse)
	err := c.cc.Invoke(ctx, MarmotService_Gossip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marmotServiceClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, MarmotService_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marmotServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, MarmotService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marmotServiceClient) ReplicateTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, MarmotService_ReplicateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marmotServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, MarmotService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marmotServiceClient) StreamChanges(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarmotService_ServiceDesc.Streams[0], MarmotService_StreamChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, ChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarmotService_StreamChangesClient = grpc.ServerStreamingClient[ChangeEvent]

func (c *marmotServiceClient) GetReplicationState(ctx context.Context, in *ReplicationStateRequest, opts ...grpc.CallOption) (*ReplicationStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicationStateResponse)
	err := c.cc.Invoke(ctx, MarmotService_GetReplicationState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marmotServiceClient) GetSnapshotInfo(ctx context.Context, in *SnapshotInfoRequest, opts ...grpc.CallOption) (*SnapshotInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotInfoResponse)
	err := c.cc.Invoke(ctx, MarmotService_GetSnapshotInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marmotServiceClient) StreamSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarmotService_ServiceDesc.Streams[1], MarmotService_StreamSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotRequest, SnapshotChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarmotService_StreamSnapshotClient = grpc.ServerStreamingClient[SnapshotChunk]

func (c *marmotServiceClient) GetLatestTxnIDs(ctx context.Context, in *LatestTxnIDsRequest, opts ...grpc.CallOption) (*LatestTxnIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LatestTxnIDsResponse)
	err := c.cc.Invoke(ctx, MarmotService_GetLatestTxnIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marmotServiceClient) GetClusterNodes(ctx context.Context, in *GetClusterNodesRequest, opts ...grpc.CallOption) (*GetClusterNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterNodesResponse)
	err := c.cc.Invoke(ctx, MarmotService_GetClusterNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marmotServiceClient) ForwardQuery(ctx context.Context, in *ForwardQueryRequest, opts ...grpc.CallOption) (*ForwardQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardQueryResponse)
	err := c.cc.Invoke(ctx, MarmotService_ForwardQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marmotServiceClient) ForwardLoadData(ctx context.Context, in *ForwardLoadDataRequest, opts ...grpc.CallOption) (*ForwardQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardQueryResponse)
	err := c.cc.Invoke(ctx, MarmotService_ForwardLoadData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marmotServiceClient) GetLoadDataChunk(ctx context.Context, in *LoadDataChunkRequest, opts ...grpc.CallOption) (*LoadDataChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadDataChunkResponse)
	err := c.cc.Invoke(ctx, MarmotService_GetLoadDataChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marmotServiceClient) TransactionStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TransactionStreamMessage, TransactionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarmotService_ServiceDesc.Streams[2], MarmotService_TransactionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransactionStreamMessage, TransactionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarmotService_TransactionStreamClient = grpc.ClientStreamingClient[TransactionStreamMessage, TransactionResponse]

// MarmotServiceServer is the server API for MarmotService service.
// All implementations must embed UnimplementedMarmotServiceServer
// for forward compatibility.
//
// Single gRPC service for all peer communication
type MarmotServiceServer interface {
	// ===== GOSSIP PROTOCOL =====
	// Periodic gossip messages (SWIM-style)
	Gossip(context.Context, *GossipRequest) (*GossipResponse, error)
	// Join cluster
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	// Heartbeat/health check
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// ===== REPLICATION =====
	// Replicate transaction (quorum writes)
	ReplicateTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error)
	// Quorum read
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	// Streaming changes (for catch-up)
	StreamChanges(*StreamRequest, grpc.ServerStreamingServer[ChangeEvent]) error
	// Get replication state (for anti-entropy)
	GetReplicationState(context.Context, *ReplicationStateRequest) (*ReplicationStateResponse, error)
	// ===== SNAPSHOT TRANSFER =====
	// Get snapshot metadata
	GetSnapshotInfo(context.Context, *SnapshotInfoRequest) (*SnapshotInfoResponse, error)
	// Stream snapshot chunks
	StreamSnapshot(*SnapshotRequest, grpc.ServerStreamingServer[SnapshotChunk]) error
	// Get latest transaction IDs per database (for delta sync detection)
	GetLatestTxnIDs(context.Context, *LatestTxnIDsRequest) (*LatestTxnIDsResponse, error)
	// GetClusterNodes returns cluster membership for readonly replicas.
	// Read-only - does not modify cluster state.
	GetClusterNodes(context.Context, *GetClusterNodesRequest) (*GetClusterNodesResponse, error)
	// Forward write query from read-only replica to leader
	ForwardQuery(context.Context, *ForwardQueryRequest) (*ForwardQueryResponse, error)
	// Forward LOAD DATA LOCAL INFILE payload from read-only replica to leader.
	ForwardLoadData(context.Context, *ForwardLoadDataRequest) (*ForwardQueryResponse, error)
	// Fetch staged LOAD DATA payload chunk by chunk.
	GetLoadDataChunk(context.Context, *LoadDataChunkRequest) (*LoadDataChunkResponse, error)
	// ===== CDC STREAMING =====
	// Client-streaming RPC for large CDC payloads (≥128KB)
	// Sends TransactionChunks followed by TransactionCommit
	TransactionStream(grpc.ClientStreamingServer[TransactionStreamMessage, TransactionResponse]) error
	mustEmbedUnimplementedMarmotServiceServer()
}

// UnimplementedMarmotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarmotServiceServer struct{}

func (UnimplementedMarmotServiceServer) Gossip(context.Context, *GossipRequest) (*GossipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Gossip not implemented")
}
func (UnimplementedMarmotServiceServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedMarmotServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMarmotServiceServer) ReplicateTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicateTransaction not implemented")
}
func (UnimplementedMarmotServiceServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedMarmotServiceServer) StreamChanges(*StreamRequest, grpc.ServerStreamingServer[ChangeEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamChanges not implemented")
}
func (UnimplementedMarmotServiceServer) GetReplicationState(context.Context, *ReplicationStateRequest) (*ReplicationStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReplicationState not implemented")
}
func (UnimplementedMarmotServiceServer) GetSnapshotInfo(context.Context, *SnapshotInfoRequest) (*SnapshotInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapshotInfo not implemented")
}
func (UnimplementedMarmotServiceServer) StreamSnapshot(*SnapshotRequest, grpc.ServerStreamingServer[SnapshotChunk]) error {
	return status.Errorf(codes.Unimplemented, "method StreamSnapshot not implemented")
}
func (UnimplementedMarmotServiceServer) GetLatestTxnIDs(context.Context, *LatestTxnIDsRequest) (*LatestTxnIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestTxnIDs not implemented")
}
func (UnimplementedMarmotServiceServer) GetClusterNodes(context.Context, *GetClusterNodesRequest) (*GetClusterNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterNodes not implemented")
}
func (UnimplementedMarmotServiceServer) ForwardQuery(context.Context, *ForwardQueryRequest) (*ForwardQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardQuery not implemented")
}
func (UnimplementedMarmotServiceServer) ForwardLoadData(context.Context, *ForwardLoadDataRequest) (*ForwardQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardLoadData not implemented")
}
func (UnimplementedMarmotServiceServer) GetLoadDataChunk(context.Context, *LoadDataChunkRequest) (*LoadDataChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoadDataChunk not implemented")
}
func (UnimplementedMarmotServiceServer) TransactionStream(grpc.ClientStreamingServer[TransactionStreamMessage, TransactionResponse]) error {
	return status.Errorf(codes.Unimplemented, "method TransactionStream not implemented")
}
func (UnimplementedMarmotServiceServer) mustEmbedUnimplementedMarmotServiceServer() {}
func (UnimplementedMarmotServiceServer) testEmbeddedByValue()                       {}

// UnsafeMarmotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarmotServiceServer will
// result in compilation errors.
type UnsafeMarmotServiceServer interface {
	mustEmbedUnimplementedMarmotServiceServer()
}

func RegisterMarmotServiceServer(s grpc.ServiceRegistrar, srv MarmotServiceServer) {
	// If the following call pancis, it indicates UnimplementedMarmotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarmotService_ServiceDesc, srv)
}

func _MarmotService_Gossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarmotServiceServer).Gossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarmotService_Gossip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarmotServiceServer).Gossip(ctx, req.(*GossipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarmotService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarmotServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarmotService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarmotServiceServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarmotService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarmotServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarmotService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarmotServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarmotService_ReplicateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarmotServiceServer).ReplicateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarmotService_ReplicateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarmotServiceServer).ReplicateTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarmotService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarmotServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarmotService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarmotServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarmotService_StreamChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarmotServiceServer).StreamChanges(m, &grpc.GenericServerStream[StreamRequest, ChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarmotService_StreamChangesServer = grpc.ServerStreamingServer[ChangeEvent]

func _MarmotService_GetReplicationState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarmotServiceServer).GetReplicationState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarmotService_GetReplicationState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarmotServiceServer).GetReplicationState(ctx, req.(*ReplicationStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarmotService_GetSnapshotInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarmotServiceServer).GetSnapshotInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarmotService_GetSnapshotInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarmotServiceServer).GetSnapshotInfo(ctx, req.(*SnapshotInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarmotService_StreamSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarmotServiceServer).StreamSnapshot(m, &grpc.GenericServerStream[SnapshotRequest, SnapshotChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarmotService_StreamSnapshotServer = grpc.ServerStreamingServer[SnapshotChunk]

func _MarmotService_GetLatestTxnIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatestTxnIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarmotServiceServer).GetLatestTxnIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarmotService_GetLatestTxnIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarmotServiceServer).GetLatestTxnIDs(ctx, req.(*LatestTxnIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarmotService_GetClusterNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarmotServiceServer).GetClusterNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarmotService_GetClusterNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarmotServiceServer).GetClusterNodes(ctx, req.(*GetClusterNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarmotService_ForwardQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarmotServiceServer).ForwardQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarmotService_ForwardQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarmotServiceServer).ForwardQuery(ctx, req.(*ForwardQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarmotService_ForwardLoadData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardLoadDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarmotServiceServer).ForwardLoadData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarmotService_ForwardLoadData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarmotServiceServer).ForwardLoadData(ctx, req.(*ForwardLoadDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarmotService_GetLoadDataChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadDataChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarmotServiceServer).GetLoadDataChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarmotService_GetLoadDataChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarmotServiceServer).GetLoadDataChunk(ctx, req.(*LoadDataChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarmotService_TransactionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MarmotServiceServer).TransactionStream(&grpc.GenericServerStream[TransactionStreamMessage, TransactionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarmotService_TransactionStreamServer = grpc.ClientStreamingServer[TransactionStreamMessage, TransactionResponse]

// MarmotService_ServiceDesc is the grpc.ServiceDesc for MarmotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarmotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marmot.v2.MarmotService",
	HandlerType: (*MarmotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Gossip",
			Handler:    _MarmotService_Gossip_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _MarmotService_Join_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _MarmotService_Ping_Handler,
		},
		{
			MethodName: "ReplicateTransaction",
			Handler:    _MarmotService_ReplicateTransaction_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _MarmotService_Read_Handler,
		},
		{
			MethodName: "GetReplicationState",
			Handler:    _MarmotService_GetReplicationState_Handler,
		},
		{
			MethodName: "GetSnapshotInfo",
			Handler:    _MarmotService_GetSnapshotInfo_Handler,
		},
		{
			MethodName: "GetLatestTxnIDs",
			Handler:    _MarmotService_GetLatestTxnIDs_Handler,
		},
		{
			MethodName: "GetClusterNodes",
			Handler:    _MarmotService_GetClusterNodes_Handler,
		},
		{
			MethodName: "ForwardQuery",
			Handler:    _MarmotService_ForwardQuery_Handler,
		},
		{
			MethodName: "ForwardLoadData",
			Handler:    _MarmotService_ForwardLoadData_Handler,
		},
		{
			MethodName: "GetLoadDataChunk",
			Handler:    _MarmotService_GetLoadDataChunk_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChanges",
			Handler:       _MarmotService_StreamChanges_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamSnapshot",
			Handler:       _MarmotService_StreamSnapshot_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TransactionStream",
			Handler:       _MarmotService_TransactionStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "grpc/marmot.proto",
}
