// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: grpc/marmot.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatus int32

const (
	NodeStatus_ALIVE   NodeStatus = 0
	NodeStatus_SUSPECT NodeStatus = 1
	NodeStatus_DEAD    NodeStatus = 2
	NodeStatus_JOINING NodeStatus = 3 // Node is catching up, receives gossip but not replication
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "ALIVE",
		1: "SUSPECT",
		2: "DEAD",
		3: "JOINING",
	}
	NodeStatus_value = map[string]int32{
		"ALIVE":   0,
		"SUSPECT": 1,
		"DEAD":    2,
		"JOINING": 3,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_marmot_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_grpc_marmot_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{0}
}

type TransactionPhase int32

const (
	TransactionPhase_PREPARE TransactionPhase = 0 // Phase 1: Create write intents
	TransactionPhase_COMMIT  TransactionPhase = 1 // Phase 2: Commit transaction
	TransactionPhase_ABORT   TransactionPhase = 2 // Abort: Rollback transaction
)

// Enum value maps for TransactionPhase.
var (
	TransactionPhase_name = map[int32]string{
		0: "PREPARE",
		1: "COMMIT",
		2: "ABORT",
	}
	TransactionPhase_value = map[string]int32{
		"PREPARE": 0,
		"COMMIT":  1,
		"ABORT":   2,
	}
)

func (x TransactionPhase) Enum() *TransactionPhase {
	p := new(TransactionPhase)
	*p = x
	return p
}

func (x TransactionPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_marmot_proto_enumTypes[1].Descriptor()
}

func (TransactionPhase) Type() protoreflect.EnumType {
	return &file_grpc_marmot_proto_enumTypes[1]
}

func (x TransactionPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionPhase.Descriptor instead.
func (TransactionPhase) EnumDescriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{1}
}

type ConsistencyLevel int32

const (
	ConsistencyLevel_CONSISTENCY_ONE    ConsistencyLevel = 0
	ConsistencyLevel_CONSISTENCY_QUORUM ConsistencyLevel = 1
	ConsistencyLevel_CONSISTENCY_ALL    ConsistencyLevel = 2
)

// Enum value maps for ConsistencyLevel.
var (
	ConsistencyLevel_name = map[int32]string{
		0: "CONSISTENCY_ONE",
		1: "CONSISTENCY_QUORUM",
		2: "CONSISTENCY_ALL",
	}
	ConsistencyLevel_value = map[string]int32{
		"CONSISTENCY_ONE":    0,
		"CONSISTENCY_QUORUM": 1,
		"CONSISTENCY_ALL":    2,
	}
)

func (x ConsistencyLevel) Enum() *ConsistencyLevel {
	p := new(ConsistencyLevel)
	*p = x
	return p
}

func (x ConsistencyLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsistencyLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_marmot_proto_enumTypes[2].Descriptor()
}

func (ConsistencyLevel) Type() protoreflect.EnumType {
	return &file_grpc_marmot_proto_enumTypes[2]
}

func (x ConsistencyLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsistencyLevel.Descriptor instead.
func (ConsistencyLevel) EnumDescriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{2}
}

type StatementType int32

const (
	StatementType_INSERT          StatementType = 0
	StatementType_UPDATE          StatementType = 1
	StatementType_DELETE          StatementType = 2
	StatementType_REPLACE         StatementType = 3
	StatementType_DDL             StatementType = 4
	StatementType_CREATE_DATABASE StatementType = 5
	StatementType_DROP_DATABASE   StatementType = 6
)

// Enum value maps for StatementType.
var (
	StatementType_name = map[int32]string{
		0: "INSERT",
		1: "UPDATE",
		2: "DELETE",
		3: "REPLACE",
		4: "DDL",
		5: "CREATE_DATABASE",
		6: "DROP_DATABASE",
	}
	StatementType_value = map[string]int32{
		"INSERT":          0,
		"UPDATE":          1,
		"DELETE":          2,
		"REPLACE":         3,
		"DDL":             4,
		"CREATE_DATABASE": 5,
		"DROP_DATABASE":   6,
	}
)

func (x StatementType) Enum() *StatementType {
	p := new(StatementType)
	*p = x
	return p
}

func (x StatementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatementType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_marmot_proto_enumTypes[3].Descriptor()
}

func (StatementType) Type() protoreflect.EnumType {
	return &file_grpc_marmot_proto_enumTypes[3]
}

func (x StatementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatementType.Descriptor instead.
func (StatementType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{3}
}

// ===== GOSSIP MESSAGES =====
type GossipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeId  uint64                 `protobuf:"varint,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	Nodes         []*NodeState           `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Incarnation   uint64                 `protobuf:"varint,3,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_grpc_marmot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{0}
}

func (x *GossipRequest) GetSourceNodeId() uint64 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

func (x *GossipRequest) GetNodes() []*NodeState {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GossipRequest) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

type GossipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeState           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_grpc_marmot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{1}
}

func (x *GossipResponse) GetNodes() []*NodeState {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeState struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NodeId      uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address     string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Status      NodeStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=marmot.v2.NodeStatus" json:"status,omitempty"`
	Incarnation uint64                 `protobuf:"varint,4,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	// Schema versions per database (for DDL drift detection)
	// key = database_name, value = schema_version
	DatabaseSchemaVersions map[string]uint64 `protobuf:"bytes,5,rep,name=database_schema_versions,json=databaseSchemaVersions,proto3" json:"database_schema_versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NodeState) Reset() {
	*x = NodeState{}
	mi := &file_grpc_marmot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState) ProtoMessage() {}

func (x *NodeState) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState.ProtoReflect.Descriptor instead.
func (*NodeState) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{2}
}

func (x *NodeState) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeState) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeState) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_ALIVE
}

func (x *NodeState) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *NodeState) GetDatabaseSchemaVersions() map[string]uint64 {
	if x != nil {
		return x.DatabaseSchemaVersions
	}
	return nil
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_grpc_marmot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *JoinRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ClusterNodes  []*NodeState           `protobuf:"bytes,2,rep,name=cluster_nodes,json=clusterNodes,proto3" json:"cluster_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_grpc_marmot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{4}
}

func (x *JoinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinResponse) GetClusterNodes() []*NodeState {
	if x != nil {
		return x.ClusterNodes
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeId  uint64                 `protobuf:"varint,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_grpc_marmot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{5}
}

func (x *PingRequest) GetSourceNodeId() uint64 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        NodeStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=marmot.v2.NodeStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_grpc_marmot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{6}
}

func (x *PingResponse) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *PingResponse) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_ALIVE
}

// ===== REPLICATION MESSAGES =====
type TransactionRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TxnId        uint64                 `protobuf:"varint,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	SourceNodeId uint64                 `protobuf:"varint,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	Statements   []*Statement           `protobuf:"bytes,3,rep,name=statements,proto3" json:"statements,omitempty"`
	Timestamp    *HLC                   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Phase for 2PC protocol
	Phase TransactionPhase `protobuf:"varint,5,opt,name=phase,proto3,enum=marmot.v2.TransactionPhase" json:"phase,omitempty"`
	// Consistency level
	Consistency ConsistencyLevel `protobuf:"varint,6,opt,name=consistency,proto3,enum=marmot.v2.ConsistencyLevel" json:"consistency,omitempty"`
	// Target database name
	Database string `protobuf:"bytes,7,opt,name=database,proto3" json:"database,omitempty"`
	// MutationGuard: table_name -> guard metadata (for multi-row mutations)
	MutationGuards map[string]*MutationGuard `protobuf:"bytes,8,rep,name=mutation_guards,json=mutationGuards,proto3" json:"mutation_guards,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_grpc_marmot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionRequest) GetTxnId() uint64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *TransactionRequest) GetSourceNodeId() uint64 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

func (x *TransactionRequest) GetStatements() []*Statement {
	if x != nil {
		return x.Statements
	}
	return nil
}

func (x *TransactionRequest) GetTimestamp() *HLC {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TransactionRequest) GetPhase() TransactionPhase {
	if x != nil {
		return x.Phase
	}
	return TransactionPhase_PREPARE
}

func (x *TransactionRequest) GetConsistency() ConsistencyLevel {
	if x != nil {
		return x.Consistency
	}
	return ConsistencyLevel_CONSISTENCY_ONE
}

func (x *TransactionRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *TransactionRequest) GetMutationGuards() map[string]*MutationGuard {
	if x != nil {
		return x.MutationGuards
	}
	return nil
}

// Per-table mutation guard metadata for conflict detection
// Used for multi-row mutations and range queries
type MutationGuard struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Binary Fuse 16 filter serialized bytes
	Filter []byte `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// Number of rows expected for this table
	ExpectedRowCount int64 `protobuf:"varint,2,opt,name=expected_row_count,json=expectedRowCount,proto3" json:"expected_row_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MutationGuard) Reset() {
	*x = MutationGuard{}
	mi := &file_grpc_marmot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationGuard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationGuard) ProtoMessage() {}

func (x *MutationGuard) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationGuard.ProtoReflect.Descriptor instead.
func (*MutationGuard) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{8}
}

func (x *MutationGuard) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *MutationGuard) GetExpectedRowCount() int64 {
	if x != nil {
		return x.ExpectedRowCount
	}
	return 0
}

// Statement represents either a DML row change or a DDL schema change
// Following industry standard CDC approach (MySQL binlog, TiDB TiCDC, CockroachDB)
type Statement struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      StatementType          `protobuf:"varint,1,opt,name=type,proto3,enum=marmot.v2.StatementType" json:"type,omitempty"`
	TableName string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Database  string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"` // Target database name (required)
	// Use oneof to clearly separate DML (row changes) from DDL (schema changes)
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Statement_RowChange
	//	*Statement_DdlChange
	Payload       isStatement_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Statement) Reset() {
	*x = Statement{}
	mi := &file_grpc_marmot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statement) ProtoMessage() {}

func (x *Statement) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statement.ProtoReflect.Descriptor instead.
func (*Statement) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{9}
}

func (x *Statement) GetType() StatementType {
	if x != nil {
		return x.Type
	}
	return StatementType_INSERT
}

func (x *Statement) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *Statement) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Statement) GetPayload() isStatement_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Statement) GetRowChange() *RowChange {
	if x != nil {
		if x, ok := x.Payload.(*Statement_RowChange); ok {
			return x.RowChange
		}
	}
	return nil
}

func (x *Statement) GetDdlChange() *DDLChange {
	if x != nil {
		if x, ok := x.Payload.(*Statement_DdlChange); ok {
			return x.DdlChange
		}
	}
	return nil
}

type isStatement_Payload interface {
	isStatement_Payload()
}

type Statement_RowChange struct {
	RowChange *RowChange `protobuf:"bytes,4,opt,name=row_change,json=rowChange,proto3,oneof"` // For INSERT/UPDATE/DELETE - actual row data
}

type Statement_DdlChange struct {
	DdlChange *DDLChange `protobuf:"bytes,5,opt,name=ddl_change,json=ddlChange,proto3,oneof"` // For DDL - SQL statement only
}

func (*Statement_RowChange) isStatement_Payload() {}

func (*Statement_DdlChange) isStatement_Payload() {}

// Row-level change data (DML operations)
// Follows MySQL binlog row format and TiDB TiCDC approach
type RowChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Primary key value for MVCC conflict detection
	RowKey string `protobuf:"bytes,1,opt,name=row_key,json=rowKey,proto3" json:"row_key,omitempty"`
	// Row images (before/after values)
	// - INSERT: only new_values populated
	// - UPDATE: both old_values and new_values populated (for conflict detection)
	// - DELETE: only old_values populated (or just row_key is sufficient)
	// - REPLACE: old_values for conflict check, new_values for data
	OldValues     map[string][]byte `protobuf:"bytes,2,rep,name=old_values,json=oldValues,proto3" json:"old_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Column name -> serialized value (before image)
	NewValues     map[string][]byte `protobuf:"bytes,3,rep,name=new_values,json=newValues,proto3" json:"new_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Column name -> serialized value (after image)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowChange) Reset() {
	*x = RowChange{}
	mi := &file_grpc_marmot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowChange) ProtoMessage() {}

func (x *RowChange) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowChange.ProtoReflect.Descriptor instead.
func (*RowChange) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{10}
}

func (x *RowChange) GetRowKey() string {
	if x != nil {
		return x.RowKey
	}
	return ""
}

func (x *RowChange) GetOldValues() map[string][]byte {
	if x != nil {
		return x.OldValues
	}
	return nil
}

func (x *RowChange) GetNewValues() map[string][]byte {
	if x != nil {
		return x.NewValues
	}
	return nil
}

// DDL schema change (CREATE/DROP/ALTER)
// DDL operations must ship SQL because schema changes cannot be represented as row data
type DDLChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"` // Transpiled SQLite DDL statement
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DDLChange) Reset() {
	*x = DDLChange{}
	mi := &file_grpc_marmot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DDLChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDLChange) ProtoMessage() {}

func (x *DDLChange) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDLChange.ProtoReflect.Descriptor instead.
func (*DDLChange) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{11}
}

func (x *DDLChange) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type HLC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WallTime      int64                  `protobuf:"varint,1,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	Logical       int32                  `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	NodeId        uint64                 `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HLC) Reset() {
	*x = HLC{}
	mi := &file_grpc_marmot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HLC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLC) ProtoMessage() {}

func (x *HLC) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLC.ProtoReflect.Descriptor instead.
func (*HLC) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{12}
}

func (x *HLC) GetWallTime() int64 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *HLC) GetLogical() int32 {
	if x != nil {
		return x.Logical
	}
	return 0
}

func (x *HLC) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type TransactionResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AppliedAt    *HLC                   `protobuf:"bytes,3,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`
	// Write-write conflict detection
	ConflictDetected bool   `protobuf:"varint,4,opt,name=conflict_detected,json=conflictDetected,proto3" json:"conflict_detected,omitempty"`
	ConflictDetails  string `protobuf:"bytes,5,opt,name=conflict_details,json=conflictDetails,proto3" json:"conflict_details,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_grpc_marmot_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{13}
}

func (x *TransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransactionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TransactionResponse) GetAppliedAt() *HLC {
	if x != nil {
		return x.AppliedAt
	}
	return nil
}

func (x *TransactionResponse) GetConflictDetected() bool {
	if x != nil {
		return x.ConflictDetected
	}
	return false
}

func (x *TransactionResponse) GetConflictDetails() string {
	if x != nil {
		return x.ConflictDetails
	}
	return ""
}

type ReadRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Query        string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	SourceNodeId uint64                 `protobuf:"varint,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	// Snapshot timestamp for MVCC reads
	SnapshotTs *HLC `protobuf:"bytes,3,opt,name=snapshot_ts,json=snapshotTs,proto3" json:"snapshot_ts,omitempty"`
	// Consistency level
	Consistency ConsistencyLevel `protobuf:"varint,4,opt,name=consistency,proto3,enum=marmot.v2.ConsistencyLevel" json:"consistency,omitempty"`
	TableName   string           `protobuf:"bytes,5,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// Target database name
	Database      string `protobuf:"bytes,6,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_grpc_marmot_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{14}
}

func (x *ReadRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ReadRequest) GetSourceNodeId() uint64 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

func (x *ReadRequest) GetSnapshotTs() *HLC {
	if x != nil {
		return x.SnapshotTs
	}
	return nil
}

func (x *ReadRequest) GetConsistency() ConsistencyLevel {
	if x != nil {
		return x.Consistency
	}
	return ConsistencyLevel_CONSISTENCY_ONE
}

func (x *ReadRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ReadRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Row                 `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Timestamp     *HLC                   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_grpc_marmot_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{15}
}

func (x *ReadResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ReadResponse) GetTimestamp() *HLC {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       map[string][]byte      `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_grpc_marmot_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{16}
}

func (x *Row) GetColumns() map[string][]byte {
	if x != nil {
		return x.Columns
	}
	return nil
}

type StreamRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FromTxnId        uint64                 `protobuf:"varint,1,opt,name=from_txn_id,json=fromTxnId,proto3" json:"from_txn_id,omitempty"`
	RequestingNodeId uint64                 `protobuf:"varint,2,opt,name=requesting_node_id,json=requestingNodeId,proto3" json:"requesting_node_id,omitempty"`
	Database         string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"` // Optional: filter by database, empty = all
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_grpc_marmot_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{17}
}

func (x *StreamRequest) GetFromTxnId() uint64 {
	if x != nil {
		return x.FromTxnId
	}
	return 0
}

func (x *StreamRequest) GetRequestingNodeId() uint64 {
	if x != nil {
		return x.RequestingNodeId
	}
	return 0
}

func (x *StreamRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type ChangeEvent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TxnId                 uint64                 `protobuf:"varint,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Statements            []*Statement           `protobuf:"bytes,2,rep,name=statements,proto3" json:"statements,omitempty"`
	Timestamp             *HLC                   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Database              string                 `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`                                                           // Target database for these changes
	RequiredSchemaVersion uint64                 `protobuf:"varint,5,opt,name=required_schema_version,json=requiredSchemaVersion,proto3" json:"required_schema_version,omitempty"` // Minimum schema version required for this transaction
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ChangeEvent) Reset() {
	*x = ChangeEvent{}
	mi := &file_grpc_marmot_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEvent) ProtoMessage() {}

func (x *ChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEvent.ProtoReflect.Descriptor instead.
func (*ChangeEvent) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{18}
}

func (x *ChangeEvent) GetTxnId() uint64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *ChangeEvent) GetStatements() []*Statement {
	if x != nil {
		return x.Statements
	}
	return nil
}

func (x *ChangeEvent) GetTimestamp() *HLC {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ChangeEvent) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ChangeEvent) GetRequiredSchemaVersion() uint64 {
	if x != nil {
		return x.RequiredSchemaVersion
	}
	return 0
}

type ReplicationStateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestingNodeId uint64                 `protobuf:"varint,1,opt,name=requesting_node_id,json=requestingNodeId,proto3" json:"requesting_node_id,omitempty"`
	Database         string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"` // Optional: filter by specific database, empty = all
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReplicationStateRequest) Reset() {
	*x = ReplicationStateRequest{}
	mi := &file_grpc_marmot_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationStateRequest) ProtoMessage() {}

func (x *ReplicationStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationStateRequest.ProtoReflect.Descriptor instead.
func (*ReplicationStateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{19}
}

func (x *ReplicationStateRequest) GetRequestingNodeId() uint64 {
	if x != nil {
		return x.RequestingNodeId
	}
	return 0
}

func (x *ReplicationStateRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type ReplicationStateResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	States        []*DatabaseReplicationState `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationStateResponse) Reset() {
	*x = ReplicationStateResponse{}
	mi := &file_grpc_marmot_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationStateResponse) ProtoMessage() {}

func (x *ReplicationStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationStateResponse.ProtoReflect.Descriptor instead.
func (*ReplicationStateResponse) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{20}
}

func (x *ReplicationStateResponse) GetStates() []*DatabaseReplicationState {
	if x != nil {
		return x.States
	}
	return nil
}

type DatabaseReplicationState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DatabaseName         string                 `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	LastAppliedTxnId     uint64                 `protobuf:"varint,2,opt,name=last_applied_txn_id,json=lastAppliedTxnId,proto3" json:"last_applied_txn_id,omitempty"`
	LastAppliedTimestamp *HLC                   `protobuf:"bytes,3,opt,name=last_applied_timestamp,json=lastAppliedTimestamp,proto3" json:"last_applied_timestamp,omitempty"`
	LastSyncTime         int64                  `protobuf:"varint,4,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	SyncStatus           string                 `protobuf:"bytes,5,opt,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty"`                         // SYNCED, CATCHING_UP, FAILED
	CurrentMaxTxnId      uint64                 `protobuf:"varint,6,opt,name=current_max_txn_id,json=currentMaxTxnId,proto3" json:"current_max_txn_id,omitempty"`     // Latest txn_id in this database
	CommittedTxnCount    int64                  `protobuf:"varint,7,opt,name=committed_txn_count,json=committedTxnCount,proto3" json:"committed_txn_count,omitempty"` // Number of committed transactions (for row count comparison)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DatabaseReplicationState) Reset() {
	*x = DatabaseReplicationState{}
	mi := &file_grpc_marmot_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseReplicationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseReplicationState) ProtoMessage() {}

func (x *DatabaseReplicationState) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseReplicationState.ProtoReflect.Descriptor instead.
func (*DatabaseReplicationState) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{21}
}

func (x *DatabaseReplicationState) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *DatabaseReplicationState) GetLastAppliedTxnId() uint64 {
	if x != nil {
		return x.LastAppliedTxnId
	}
	return 0
}

func (x *DatabaseReplicationState) GetLastAppliedTimestamp() *HLC {
	if x != nil {
		return x.LastAppliedTimestamp
	}
	return nil
}

func (x *DatabaseReplicationState) GetLastSyncTime() int64 {
	if x != nil {
		return x.LastSyncTime
	}
	return 0
}

func (x *DatabaseReplicationState) GetSyncStatus() string {
	if x != nil {
		return x.SyncStatus
	}
	return ""
}

func (x *DatabaseReplicationState) GetCurrentMaxTxnId() uint64 {
	if x != nil {
		return x.CurrentMaxTxnId
	}
	return 0
}

func (x *DatabaseReplicationState) GetCommittedTxnCount() int64 {
	if x != nil {
		return x.CommittedTxnCount
	}
	return 0
}

// ===== SNAPSHOT MESSAGES =====
type SnapshotInfoRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestingNodeId uint64                 `protobuf:"varint,1,opt,name=requesting_node_id,json=requestingNodeId,proto3" json:"requesting_node_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SnapshotInfoRequest) Reset() {
	*x = SnapshotInfoRequest{}
	mi := &file_grpc_marmot_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInfoRequest) ProtoMessage() {}

func (x *SnapshotInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInfoRequest.ProtoReflect.Descriptor instead.
func (*SnapshotInfoRequest) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{22}
}

func (x *SnapshotInfoRequest) GetRequestingNodeId() uint64 {
	if x != nil {
		return x.RequestingNodeId
	}
	return 0
}

type SnapshotInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SnapshotTxnId     uint64                 `protobuf:"varint,1,opt,name=snapshot_txn_id,json=snapshotTxnId,proto3" json:"snapshot_txn_id,omitempty"`
	SnapshotSizeBytes int64                  `protobuf:"varint,2,opt,name=snapshot_size_bytes,json=snapshotSizeBytes,proto3" json:"snapshot_size_bytes,omitempty"`
	TotalChunks       int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Timestamp         *HLC                   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Databases         []*DatabaseFileInfo    `protobuf:"bytes,5,rep,name=databases,proto3" json:"databases,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SnapshotInfoResponse) Reset() {
	*x = SnapshotInfoResponse{}
	mi := &file_grpc_marmot_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInfoResponse) ProtoMessage() {}

func (x *SnapshotInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInfoResponse.ProtoReflect.Descriptor instead.
func (*SnapshotInfoResponse) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{23}
}

func (x *SnapshotInfoResponse) GetSnapshotTxnId() uint64 {
	if x != nil {
		return x.SnapshotTxnId
	}
	return 0
}

func (x *SnapshotInfoResponse) GetSnapshotSizeBytes() int64 {
	if x != nil {
		return x.SnapshotSizeBytes
	}
	return 0
}

func (x *SnapshotInfoResponse) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *SnapshotInfoResponse) GetTimestamp() *HLC {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SnapshotInfoResponse) GetDatabases() []*DatabaseFileInfo {
	if x != nil {
		return x.Databases
	}
	return nil
}

type DatabaseFileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // Database name (e.g., "marmot", "__marmot_system")
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"` // Relative path
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseFileInfo) Reset() {
	*x = DatabaseFileInfo{}
	mi := &file_grpc_marmot_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseFileInfo) ProtoMessage() {}

func (x *DatabaseFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseFileInfo.ProtoReflect.Descriptor instead.
func (*DatabaseFileInfo) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{24}
}

func (x *DatabaseFileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DatabaseFileInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DatabaseFileInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type SnapshotRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestingNodeId uint64                 `protobuf:"varint,1,opt,name=requesting_node_id,json=requestingNodeId,proto3" json:"requesting_node_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_grpc_marmot_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{25}
}

func (x *SnapshotRequest) GetRequestingNodeId() uint64 {
	if x != nil {
		return x.RequestingNodeId
	}
	return 0
}

type SnapshotChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkIndex    int32                  `protobuf:"varint,1,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Filename      string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`                                     // Which database file this chunk belongs to
	IsLastForFile bool                   `protobuf:"varint,6,opt,name=is_last_for_file,json=isLastForFile,proto3" json:"is_last_for_file,omitempty"` // True if this is the last chunk for this file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotChunk) Reset() {
	*x = SnapshotChunk{}
	mi := &file_grpc_marmot_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunk) ProtoMessage() {}

func (x *SnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunk.ProtoReflect.Descriptor instead.
func (*SnapshotChunk) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{26}
}

func (x *SnapshotChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *SnapshotChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *SnapshotChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotChunk) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *SnapshotChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SnapshotChunk) GetIsLastForFile() bool {
	if x != nil {
		return x.IsLastForFile
	}
	return false
}

// ===== DELTA SYNC DETECTION =====
type LatestTxnIDsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestingNodeId uint64                 `protobuf:"varint,1,opt,name=requesting_node_id,json=requestingNodeId,proto3" json:"requesting_node_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LatestTxnIDsRequest) Reset() {
	*x = LatestTxnIDsRequest{}
	mi := &file_grpc_marmot_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestTxnIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestTxnIDsRequest) ProtoMessage() {}

func (x *LatestTxnIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestTxnIDsRequest.ProtoReflect.Descriptor instead.
func (*LatestTxnIDsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{27}
}

func (x *LatestTxnIDsRequest) GetRequestingNodeId() uint64 {
	if x != nil {
		return x.RequestingNodeId
	}
	return 0
}

type LatestTxnIDsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of database name to latest committed txn_id
	DatabaseTxnIds map[string]uint64 `protobuf:"bytes,1,rep,name=database_txn_ids,json=databaseTxnIds,proto3" json:"database_txn_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LatestTxnIDsResponse) Reset() {
	*x = LatestTxnIDsResponse{}
	mi := &file_grpc_marmot_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestTxnIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestTxnIDsResponse) ProtoMessage() {}

func (x *LatestTxnIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_marmot_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestTxnIDsResponse.ProtoReflect.Descriptor instead.
func (*LatestTxnIDsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_marmot_proto_rawDescGZIP(), []int{28}
}

func (x *LatestTxnIDsResponse) GetDatabaseTxnIds() map[string]uint64 {
	if x != nil {
		return x.DatabaseTxnIds
	}
	return nil
}

var File_grpc_marmot_proto protoreflect.FileDescriptor

const file_grpc_marmot_proto_rawDesc = "" +
	"\n" +
	"\x11grpc/marmot.proto\x12\tmarmot.v2\"\x83\x01\n" +
	"\rGossipRequest\x12$\n" +
	"\x0esource_node_id\x18\x01 \x01(\x04R\fsourceNodeId\x12*\n" +
	"\x05nodes\x18\x02 \x03(\v2\x14.marmot.v2.NodeStateR\x05nodes\x12 \n" +
	"\vincarnation\x18\x03 \x01(\x04R\vincarnation\"<\n" +
	"\x0eGossipResponse\x12*\n" +
	"\x05nodes\x18\x01 \x03(\v2\x14.marmot.v2.NodeStateR\x05nodes\"\xc6\x02\n" +
	"\tNodeState\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.marmot.v2.NodeStatusR\x06status\x12 \n" +
	"\vincarnation\x18\x04 \x01(\x04R\vincarnation\x12j\n" +
	"\x18database_schema_versions\x18\x05 \x03(\v20.marmot.v2.NodeState.DatabaseSchemaVersionsEntryR\x16databaseSchemaVersions\x1aI\n" +
	"\x1bDatabaseSchemaVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"@\n" +
	"\vJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"c\n" +
	"\fJoinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x129\n" +
	"\rcluster_nodes\x18\x02 \x03(\v2\x14.marmot.v2.NodeStateR\fclusterNodes\"3\n" +
	"\vPingRequest\x12$\n" +
	"\x0esource_node_id\x18\x01 \x01(\x04R\fsourceNodeId\"V\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.marmot.v2.NodeStatusR\x06status\"\xfc\x03\n" +
	"\x12TransactionRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\x04R\x05txnId\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\x04R\fsourceNodeId\x124\n" +
	"\n" +
	"statements\x18\x03 \x03(\v2\x14.marmot.v2.StatementR\n" +
	"statements\x12,\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x0e.marmot.v2.HLCR\ttimestamp\x121\n" +
	"\x05phase\x18\x05 \x01(\x0e2\x1b.marmot.v2.TransactionPhaseR\x05phase\x12=\n" +
	"\vconsistency\x18\x06 \x01(\x0e2\x1b.marmot.v2.ConsistencyLevelR\vconsistency\x12\x1a\n" +
	"\bdatabase\x18\a \x01(\tR\bdatabase\x12Z\n" +
	"\x0fmutation_guards\x18\b \x03(\v21.marmot.v2.TransactionRequest.MutationGuardsEntryR\x0emutationGuards\x1a[\n" +
	"\x13MutationGuardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.marmot.v2.MutationGuardR\x05value:\x028\x01\"U\n" +
	"\rMutationGuard\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\fR\x06filter\x12,\n" +
	"\x12expected_row_count\x18\x02 \x01(\x03R\x10expectedRowCount\"\xed\x01\n" +
	"\tStatement\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.marmot.v2.StatementTypeR\x04type\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x125\n" +
	"\n" +
	"row_change\x18\x04 \x01(\v2\x14.marmot.v2.RowChangeH\x00R\trowChange\x125\n" +
	"\n" +
	"ddl_change\x18\x05 \x01(\v2\x14.marmot.v2.DDLChangeH\x00R\tddlChangeB\t\n" +
	"\apayload\"\xa8\x02\n" +
	"\tRowChange\x12\x17\n" +
	"\arow_key\x18\x01 \x01(\tR\x06rowKey\x12B\n" +
	"\n" +
	"old_values\x18\x02 \x03(\v2#.marmot.v2.RowChange.OldValuesEntryR\toldValues\x12B\n" +
	"\n" +
	"new_values\x18\x03 \x03(\v2#.marmot.v2.RowChange.NewValuesEntryR\tnewValues\x1a<\n" +
	"\x0eOldValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a<\n" +
	"\x0eNewValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x1d\n" +
	"\tDDLChange\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\"U\n" +
	"\x03HLC\x12\x1b\n" +
	"\twall_time\x18\x01 \x01(\x03R\bwallTime\x12\x18\n" +
	"\alogical\x18\x02 \x01(\x05R\alogical\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x04R\x06nodeId\"\xdb\x01\n" +
	"\x13TransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12-\n" +
	"\n" +
	"applied_at\x18\x03 \x01(\v2\x0e.marmot.v2.HLCR\tappliedAt\x12+\n" +
	"\x11conflict_detected\x18\x04 \x01(\bR\x10conflictDetected\x12)\n" +
	"\x10conflict_details\x18\x05 \x01(\tR\x0fconflictDetails\"\xf4\x01\n" +
	"\vReadRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\x04R\fsourceNodeId\x12/\n" +
	"\vsnapshot_ts\x18\x03 \x01(\v2\x0e.marmot.v2.HLCR\n" +
	"snapshotTs\x12=\n" +
	"\vconsistency\x18\x04 \x01(\x0e2\x1b.marmot.v2.ConsistencyLevelR\vconsistency\x12\x1d\n" +
	"\n" +
	"table_name\x18\x05 \x01(\tR\ttableName\x12\x1a\n" +
	"\bdatabase\x18\x06 \x01(\tR\bdatabase\"`\n" +
	"\fReadResponse\x12\"\n" +
	"\x04rows\x18\x01 \x03(\v2\x0e.marmot.v2.RowR\x04rows\x12,\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x0e.marmot.v2.HLCR\ttimestamp\"x\n" +
	"\x03Row\x125\n" +
	"\acolumns\x18\x01 \x03(\v2\x1b.marmot.v2.Row.ColumnsEntryR\acolumns\x1a:\n" +
	"\fColumnsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"y\n" +
	"\rStreamRequest\x12\x1e\n" +
	"\vfrom_txn_id\x18\x01 \x01(\x04R\tfromTxnId\x12,\n" +
	"\x12requesting_node_id\x18\x02 \x01(\x04R\x10requestingNodeId\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\"\xdc\x01\n" +
	"\vChangeEvent\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\x04R\x05txnId\x124\n" +
	"\n" +
	"statements\x18\x02 \x03(\v2\x14.marmot.v2.StatementR\n" +
	"statements\x12,\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x0e.marmot.v2.HLCR\ttimestamp\x12\x1a\n" +
	"\bdatabase\x18\x04 \x01(\tR\bdatabase\x126\n" +
	"\x17required_schema_version\x18\x05 \x01(\x04R\x15requiredSchemaVersion\"c\n" +
	"\x17ReplicationStateRequest\x12,\n" +
	"\x12requesting_node_id\x18\x01 \x01(\x04R\x10requestingNodeId\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\"W\n" +
	"\x18ReplicationStateResponse\x12;\n" +
	"\x06states\x18\x01 \x03(\v2#.marmot.v2.DatabaseReplicationStateR\x06states\"\xd8\x02\n" +
	"\x18DatabaseReplicationState\x12#\n" +
	"\rdatabase_name\x18\x01 \x01(\tR\fdatabaseName\x12-\n" +
	"\x13last_applied_txn_id\x18\x02 \x01(\x04R\x10lastAppliedTxnId\x12D\n" +
	"\x16last_applied_timestamp\x18\x03 \x01(\v2\x0e.marmot.v2.HLCR\x14lastAppliedTimestamp\x12$\n" +
	"\x0elast_sync_time\x18\x04 \x01(\x03R\flastSyncTime\x12\x1f\n" +
	"\vsync_status\x18\x05 \x01(\tR\n" +
	"syncStatus\x12+\n" +
	"\x12current_max_txn_id\x18\x06 \x01(\x04R\x0fcurrentMaxTxnId\x12.\n" +
	"\x13committed_txn_count\x18\a \x01(\x03R\x11committedTxnCount\"C\n" +
	"\x13SnapshotInfoRequest\x12,\n" +
	"\x12requesting_node_id\x18\x01 \x01(\x04R\x10requestingNodeId\"\xfa\x01\n" +
	"\x14SnapshotInfoResponse\x12&\n" +
	"\x0fsnapshot_txn_id\x18\x01 \x01(\x04R\rsnapshotTxnId\x12.\n" +
	"\x13snapshot_size_bytes\x18\x02 \x01(\x03R\x11snapshotSizeBytes\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\x12,\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x0e.marmot.v2.HLCR\ttimestamp\x129\n" +
	"\tdatabases\x18\x05 \x03(\v2\x1b.marmot.v2.DatabaseFileInfoR\tdatabases\"a\n" +
	"\x10DatabaseFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"?\n" +
	"\x0fSnapshotRequest\x12,\n" +
	"\x12requesting_node_id\x18\x01 \x01(\x04R\x10requestingNodeId\"\xc8\x01\n" +
	"\rSnapshotChunk\x12\x1f\n" +
	"\vchunk_index\x18\x01 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\x05R\vtotalChunks\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12'\n" +
	"\x10is_last_for_file\x18\x06 \x01(\bR\risLastForFile\"C\n" +
	"\x13LatestTxnIDsRequest\x12,\n" +
	"\x12requesting_node_id\x18\x01 \x01(\x04R\x10requestingNodeId\"\xb8\x01\n" +
	"\x14LatestTxnIDsResponse\x12]\n" +
	"\x10database_txn_ids\x18\x01 \x03(\v23.marmot.v2.LatestTxnIDsResponse.DatabaseTxnIdsEntryR\x0edatabaseTxnIds\x1aA\n" +
	"\x13DatabaseTxnIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01*;\n" +
	"\n" +
	"NodeStatus\x12\t\n" +
	"\x05ALIVE\x10\x00\x12\v\n" +
	"\aSUSPECT\x10\x01\x12\b\n" +
	"\x04DEAD\x10\x02\x12\v\n" +
	"\aJOINING\x10\x03*6\n" +
	"\x10TransactionPhase\x12\v\n" +
	"\aPREPARE\x10\x00\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x01\x12\t\n" +
	"\x05ABORT\x10\x02*T\n" +
	"\x10ConsistencyLevel\x12\x13\n" +
	"\x0fCONSISTENCY_ONE\x10\x00\x12\x16\n" +
	"\x12CONSISTENCY_QUORUM\x10\x01\x12\x13\n" +
	"\x0fCONSISTENCY_ALL\x10\x02*q\n" +
	"\rStatementType\x12\n" +
	"\n" +
	"\x06INSERT\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\x12\v\n" +
	"\aREPLACE\x10\x03\x12\a\n" +
	"\x03DDL\x10\x04\x12\x13\n" +
	"\x0fCREATE_DATABASE\x10\x05\x12\x11\n" +
	"\rDROP_DATABASE\x10\x062\xe7\x05\n" +
	"\rMarmotService\x12=\n" +
	"\x06Gossip\x12\x18.marmot.v2.GossipRequest\x1a\x19.marmot.v2.GossipResponse\x127\n" +
	"\x04Join\x12\x16.marmot.v2.JoinRequest\x1a\x17.marmot.v2.JoinResponse\x127\n" +
	"\x04Ping\x12\x16.marmot.v2.PingRequest\x1a\x17.marmot.v2.PingResponse\x12U\n" +
	"\x14ReplicateTransaction\x12\x1d.marmot.v2.TransactionRequest\x1a\x1e.marmot.v2.TransactionResponse\x127\n" +
	"\x04Read\x12\x16.marmot.v2.ReadRequest\x1a\x17.marmot.v2.ReadResponse\x12C\n" +
	"\rStreamChanges\x12\x18.marmot.v2.StreamRequest\x1a\x16.marmot.v2.ChangeEvent0\x01\x12^\n" +
	"\x13GetReplicationState\x12\".marmot.v2.ReplicationStateRequest\x1a#.marmot.v2.ReplicationStateResponse\x12R\n" +
	"\x0fGetSnapshotInfo\x12\x1e.marmot.v2.SnapshotInfoRequest\x1a\x1f.marmot.v2.SnapshotInfoResponse\x12H\n" +
	"\x0eStreamSnapshot\x12\x1a.marmot.v2.SnapshotRequest\x1a\x18.marmot.v2.SnapshotChunk0\x01\x12R\n" +
	"\x0fGetLatestTxnIDs\x12\x1e.marmot.v2.LatestTxnIDsRequest\x1a\x1f.marmot.v2.LatestTxnIDsResponseB Z\x1egithub.com/maxpert/marmot/grpcb\x06proto3"

var (
	file_grpc_marmot_proto_rawDescOnce sync.Once
	file_grpc_marmot_proto_rawDescData []byte
)

func file_grpc_marmot_proto_rawDescGZIP() []byte {
	file_grpc_marmot_proto_rawDescOnce.Do(func() {
		file_grpc_marmot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_marmot_proto_rawDesc), len(file_grpc_marmot_proto_rawDesc)))
	})
	return file_grpc_marmot_proto_rawDescData
}

var file_grpc_marmot_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_grpc_marmot_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_grpc_marmot_proto_goTypes = []any{
	(NodeStatus)(0),                  // 0: marmot.v2.NodeStatus
	(TransactionPhase)(0),            // 1: marmot.v2.TransactionPhase
	(ConsistencyLevel)(0),            // 2: marmot.v2.ConsistencyLevel
	(StatementType)(0),               // 3: marmot.v2.StatementType
	(*GossipRequest)(nil),            // 4: marmot.v2.GossipRequest
	(*GossipResponse)(nil),           // 5: marmot.v2.GossipResponse
	(*NodeState)(nil),                // 6: marmot.v2.NodeState
	(*JoinRequest)(nil),              // 7: marmot.v2.JoinRequest
	(*JoinResponse)(nil),             // 8: marmot.v2.JoinResponse
	(*PingRequest)(nil),              // 9: marmot.v2.PingRequest
	(*PingResponse)(nil),             // 10: marmot.v2.PingResponse
	(*TransactionRequest)(nil),       // 11: marmot.v2.TransactionRequest
	(*MutationGuard)(nil),            // 12: marmot.v2.MutationGuard
	(*Statement)(nil),                // 13: marmot.v2.Statement
	(*RowChange)(nil),                // 14: marmot.v2.RowChange
	(*DDLChange)(nil),                // 15: marmot.v2.DDLChange
	(*HLC)(nil),                      // 16: marmot.v2.HLC
	(*TransactionResponse)(nil),      // 17: marmot.v2.TransactionResponse
	(*ReadRequest)(nil),              // 18: marmot.v2.ReadRequest
	(*ReadResponse)(nil),             // 19: marmot.v2.ReadResponse
	(*Row)(nil),                      // 20: marmot.v2.Row
	(*StreamRequest)(nil),            // 21: marmot.v2.StreamRequest
	(*ChangeEvent)(nil),              // 22: marmot.v2.ChangeEvent
	(*ReplicationStateRequest)(nil),  // 23: marmot.v2.ReplicationStateRequest
	(*ReplicationStateResponse)(nil), // 24: marmot.v2.ReplicationStateResponse
	(*DatabaseReplicationState)(nil), // 25: marmot.v2.DatabaseReplicationState
	(*SnapshotInfoRequest)(nil),      // 26: marmot.v2.SnapshotInfoRequest
	(*SnapshotInfoResponse)(nil),     // 27: marmot.v2.SnapshotInfoResponse
	(*DatabaseFileInfo)(nil),         // 28: marmot.v2.DatabaseFileInfo
	(*SnapshotRequest)(nil),          // 29: marmot.v2.SnapshotRequest
	(*SnapshotChunk)(nil),            // 30: marmot.v2.SnapshotChunk
	(*LatestTxnIDsRequest)(nil),      // 31: marmot.v2.LatestTxnIDsRequest
	(*LatestTxnIDsResponse)(nil),     // 32: marmot.v2.LatestTxnIDsResponse
	nil,                              // 33: marmot.v2.NodeState.DatabaseSchemaVersionsEntry
	nil,                              // 34: marmot.v2.TransactionRequest.MutationGuardsEntry
	nil,                              // 35: marmot.v2.RowChange.OldValuesEntry
	nil,                              // 36: marmot.v2.RowChange.NewValuesEntry
	nil,                              // 37: marmot.v2.Row.ColumnsEntry
	nil,                              // 38: marmot.v2.LatestTxnIDsResponse.DatabaseTxnIdsEntry
}
var file_grpc_marmot_proto_depIdxs = []int32{
	6,  // 0: marmot.v2.GossipRequest.nodes:type_name -> marmot.v2.NodeState
	6,  // 1: marmot.v2.GossipResponse.nodes:type_name -> marmot.v2.NodeState
	0,  // 2: marmot.v2.NodeState.status:type_name -> marmot.v2.NodeStatus
	33, // 3: marmot.v2.NodeState.database_schema_versions:type_name -> marmot.v2.NodeState.DatabaseSchemaVersionsEntry
	6,  // 4: marmot.v2.JoinResponse.cluster_nodes:type_name -> marmot.v2.NodeState
	0,  // 5: marmot.v2.PingResponse.status:type_name -> marmot.v2.NodeStatus
	13, // 6: marmot.v2.TransactionRequest.statements:type_name -> marmot.v2.Statement
	16, // 7: marmot.v2.TransactionRequest.timestamp:type_name -> marmot.v2.HLC
	1,  // 8: marmot.v2.TransactionRequest.phase:type_name -> marmot.v2.TransactionPhase
	2,  // 9: marmot.v2.TransactionRequest.consistency:type_name -> marmot.v2.ConsistencyLevel
	34, // 10: marmot.v2.TransactionRequest.mutation_guards:type_name -> marmot.v2.TransactionRequest.MutationGuardsEntry
	3,  // 11: marmot.v2.Statement.type:type_name -> marmot.v2.StatementType
	14, // 12: marmot.v2.Statement.row_change:type_name -> marmot.v2.RowChange
	15, // 13: marmot.v2.Statement.ddl_change:type_name -> marmot.v2.DDLChange
	35, // 14: marmot.v2.RowChange.old_values:type_name -> marmot.v2.RowChange.OldValuesEntry
	36, // 15: marmot.v2.RowChange.new_values:type_name -> marmot.v2.RowChange.NewValuesEntry
	16, // 16: marmot.v2.TransactionResponse.applied_at:type_name -> marmot.v2.HLC
	16, // 17: marmot.v2.ReadRequest.snapshot_ts:type_name -> marmot.v2.HLC
	2,  // 18: marmot.v2.ReadRequest.consistency:type_name -> marmot.v2.ConsistencyLevel
	20, // 19: marmot.v2.ReadResponse.rows:type_name -> marmot.v2.Row
	16, // 20: marmot.v2.ReadResponse.timestamp:type_name -> marmot.v2.HLC
	37, // 21: marmot.v2.Row.columns:type_name -> marmot.v2.Row.ColumnsEntry
	13, // 22: marmot.v2.ChangeEvent.statements:type_name -> marmot.v2.Statement
	16, // 23: marmot.v2.ChangeEvent.timestamp:type_name -> marmot.v2.HLC
	25, // 24: marmot.v2.ReplicationStateResponse.states:type_name -> marmot.v2.DatabaseReplicationState
	16, // 25: marmot.v2.DatabaseReplicationState.last_applied_timestamp:type_name -> marmot.v2.HLC
	16, // 26: marmot.v2.SnapshotInfoResponse.timestamp:type_name -> marmot.v2.HLC
	28, // 27: marmot.v2.SnapshotInfoResponse.databases:type_name -> marmot.v2.DatabaseFileInfo
	38, // 28: marmot.v2.LatestTxnIDsResponse.database_txn_ids:type_name -> marmot.v2.LatestTxnIDsResponse.DatabaseTxnIdsEntry
	12, // 29: marmot.v2.TransactionRequest.MutationGuardsEntry.value:type_name -> marmot.v2.MutationGuard
	4,  // 30: marmot.v2.MarmotService.Gossip:input_type -> marmot.v2.GossipRequest
	7,  // 31: marmot.v2.MarmotService.Join:input_type -> marmot.v2.JoinRequest
	9,  // 32: marmot.v2.MarmotService.Ping:input_type -> marmot.v2.PingRequest
	11, // 33: marmot.v2.MarmotService.ReplicateTransaction:input_type -> marmot.v2.TransactionRequest
	18, // 34: marmot.v2.MarmotService.Read:input_type -> marmot.v2.ReadRequest
	21, // 35: marmot.v2.MarmotService.StreamChanges:input_type -> marmot.v2.StreamRequest
	23, // 36: marmot.v2.MarmotService.GetReplicationState:input_type -> marmot.v2.ReplicationStateRequest
	26, // 37: marmot.v2.MarmotService.GetSnapshotInfo:input_type -> marmot.v2.SnapshotInfoRequest
	29, // 38: marmot.v2.MarmotService.StreamSnapshot:input_type -> marmot.v2.SnapshotRequest
	31, // 39: marmot.v2.MarmotService.GetLatestTxnIDs:input_type -> marmot.v2.LatestTxnIDsRequest
	5,  // 40: marmot.v2.MarmotService.Gossip:output_type -> marmot.v2.GossipResponse
	8,  // 41: marmot.v2.MarmotService.Join:output_type -> marmot.v2.JoinResponse
	10, // 42: marmot.v2.MarmotService.Ping:output_type -> marmot.v2.PingResponse
	17, // 43: marmot.v2.MarmotService.ReplicateTransaction:output_type -> marmot.v2.TransactionResponse
	19, // 44: marmot.v2.MarmotService.Read:output_type -> marmot.v2.ReadResponse
	22, // 45: marmot.v2.MarmotService.StreamChanges:output_type -> marmot.v2.ChangeEvent
	24, // 46: marmot.v2.MarmotService.GetReplicationState:output_type -> marmot.v2.ReplicationStateResponse
	27, // 47: marmot.v2.MarmotService.GetSnapshotInfo:output_type -> marmot.v2.SnapshotInfoResponse
	30, // 48: marmot.v2.MarmotService.StreamSnapshot:output_type -> marmot.v2.SnapshotChunk
	32, // 49: marmot.v2.MarmotService.GetLatestTxnIDs:output_type -> marmot.v2.LatestTxnIDsResponse
	40, // [40:50] is the sub-list for method output_type
	30, // [30:40] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_grpc_marmot_proto_init() }
func file_grpc_marmot_proto_init() {
	if File_grpc_marmot_proto != nil {
		return
	}
	file_grpc_marmot_proto_msgTypes[9].OneofWrappers = []any{
		(*Statement_RowChange)(nil),
		(*Statement_DdlChange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_marmot_proto_rawDesc), len(file_grpc_marmot_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_marmot_proto_goTypes,
		DependencyIndexes: file_grpc_marmot_proto_depIdxs,
		EnumInfos:         file_grpc_marmot_proto_enumTypes,
		MessageInfos:      file_grpc_marmot_proto_msgTypes,
	}.Build()
	File_grpc_marmot_proto = out.File
	file_grpc_marmot_proto_goTypes = nil
	file_grpc_marmot_proto_depIdxs = nil
}
