#!/bin/bash
#
# Join an existing Marmot cluster as a new node
#
# Usage: ./join-cluster.sh <node_id> <seed_address>
#
# Example:
#   # Start seed node first (in another terminal):
#   ./marmot-v2 --config config.toml
#
#   # Join as node 2:
#   ./join-cluster.sh 2 localhost:5001
#
#   # Join as node 3:
#   ./join-cluster.sh 3 localhost:5001

set -e

NODE_ID=${1:-2}
SEED_ADDR=${2:-"localhost:5001"}

# Calculate ports based on node ID
# Node 1: mysql=3306, grpc=5001
# Node 2: mysql=3307, grpc=5002
# etc.
MYSQL_PORT=$((3305 + NODE_ID))
GRPC_PORT=$((5000 + NODE_ID))

# Directories
DATA_DIR="/tmp/marmot-node-${NODE_ID}"
CONFIG_FILE="/tmp/marmot-node-${NODE_ID}.toml"

echo "=== Marmot Cluster Join ==="
echo "Node ID:     ${NODE_ID}"
echo "Seed:        ${SEED_ADDR}"
echo "MySQL Port:  ${MYSQL_PORT}"
echo "gRPC Port:   ${GRPC_PORT}"
echo "Data Dir:    ${DATA_DIR}"
echo "Config:      ${CONFIG_FILE}"
echo ""

# Clean up previous data (optional - comment out to preserve data)
if [ -d "${DATA_DIR}" ]; then
    echo "Cleaning up previous data directory..."
    rm -rf "${DATA_DIR}"
fi

mkdir -p "${DATA_DIR}"

# Generate config file
cat > "${CONFIG_FILE}" << EOF
# Marmot Node ${NODE_ID} Configuration
# Auto-generated by join-cluster.sh

[node]
id = ${NODE_ID}

[storage]
data_dir = "${DATA_DIR}"

[mysql]
enabled = true
address = "0.0.0.0"
port = ${MYSQL_PORT}

[grpc]
address = "0.0.0.0"
port = ${GRPC_PORT}

[cluster]
seeds = ["${SEED_ADDR}"]

[replication]
write_timeout_ms = 5000
read_timeout_ms = 2000

[gossip]
interval_ms = 1000
suspect_timeout_ms = 5000
dead_timeout_ms = 15000

[logging]
level = "info"
format = "console"
EOF

echo "Generated config:"
echo "---"
cat "${CONFIG_FILE}"
echo "---"
echo ""

# Find marmot binary
MARMOT_BIN=""
if [ -f "./marmot-v2" ]; then
    MARMOT_BIN="./marmot-v2"
elif [ -f "./marmot" ]; then
    MARMOT_BIN="./marmot"
elif [ -f "../marmot-v2" ]; then
    MARMOT_BIN="../marmot-v2"
elif [ -f "../marmot" ]; then
    MARMOT_BIN="../marmot"
else
    echo "Building marmot..."
    cd "$(dirname "$0")/.."
    go build -o marmot-v2 .
    MARMOT_BIN="./marmot-v2"
fi

echo "Starting Marmot node ${NODE_ID}..."
echo "Connect with: mysql -h localhost -P ${MYSQL_PORT} -u root"
echo ""

exec ${MARMOT_BIN} --config "${CONFIG_FILE}"
