#!/bin/bash
#
# Join an existing Marmot cluster as a new node
#
# Usage: ./join-cluster.sh <node_id> <seed_address>
#
# Example:
#   # Start seed node first (in another terminal):
#   ./examples/start-seed.sh
#
#   # Join as node 2:
#   ./join-cluster.sh 2 localhost:8081
#
#   # Join as node 3:
#   ./join-cluster.sh 3 localhost:8081

set -e

NODE_ID=${1:-2}
SEED_ADDR=${2:-"localhost:8081"}

# Calculate ports based on node ID
# Node 1: mysql=3307, grpc=8081
# Node 2: mysql=3308, grpc=8082
# etc.
MYSQL_PORT=$((3306 + NODE_ID))
GRPC_PORT=$((8080 + NODE_ID))

# Directories
DATA_DIR="/tmp/marmot-node-${NODE_ID}"
CONFIG_FILE="/tmp/marmot-node-${NODE_ID}.toml"

echo "=== Marmot Cluster Join ==="
echo "Node ID:     ${NODE_ID}"
echo "Seed:        ${SEED_ADDR}"
echo "MySQL Port:  ${MYSQL_PORT}"
echo "gRPC Port:   ${GRPC_PORT}"
echo "Data Dir:    ${DATA_DIR}"
echo "Config:      ${CONFIG_FILE}"
echo ""

# Clean up previous data (optional - comment out to preserve data)
if [ -d "${DATA_DIR}" ]; then
    echo "Cleaning up previous data directory..."
    rm -rf "${DATA_DIR}"
fi

mkdir -p "${DATA_DIR}"

# Generate config file
cat > "${CONFIG_FILE}" << EOF
# Marmot Node ${NODE_ID} Configuration
# Auto-generated by join-cluster.sh

data_dir = "${DATA_DIR}"

[cluster]
grpc_bind_address = "0.0.0.0"
grpc_port = ${GRPC_PORT}
grpc_advertise_address = "localhost:${GRPC_PORT}"
seed_nodes = ["${SEED_ADDR}"]
gossip_interval_ms = 1000
gossip_fanout = 3
suspect_timeout_ms = 5000
dead_timeout_ms = 15000

[mysql]
enabled = true
bind_address = "0.0.0.0"
port = ${MYSQL_PORT}

[replication]
default_write_consistency = "QUORUM"  # Replicate to majority
default_read_consistency = "LOCAL_ONE"
write_timeout_ms = 5000
read_timeout_ms = 2000
enable_anti_entropy = true
anti_entropy_interval_seconds = 60

[logging]
verbose = true
format = "console"
EOF

echo "Generated config:"
echo "---"
cat "${CONFIG_FILE}"
echo "---"
echo ""

# Find marmot binary
MARMOT_BIN=""
if [ -f "./marmot-v2" ]; then
    MARMOT_BIN="./marmot-v2"
elif [ -f "./marmot" ]; then
    MARMOT_BIN="./marmot"
elif [ -f "../marmot-v2" ]; then
    MARMOT_BIN="../marmot-v2"
elif [ -f "../marmot" ]; then
    MARMOT_BIN="../marmot"
else
    echo "Building marmot..."
    cd "$(dirname "$0")/.."
    go build -o marmot-v2 .
    MARMOT_BIN="./marmot-v2"
fi

echo "Starting Marmot node ${NODE_ID}..."
echo "Connect with: mysql -h localhost -P ${MYSQL_PORT} -u root"
echo ""

exec ${MARMOT_BIN} --config "${CONFIG_FILE}"
