#!/bin/bash
#
# Join an existing Marmot cluster as a new node
#
# Usage: ./join-cluster.sh <node_id> <seed_address>
#
# Example:
#   # Start seed node first (in another terminal):
#   ./examples/start-seed.sh
#
#   # Join as node 2:
#   ./join-cluster.sh 2 localhost:8081
#
#   # Join as node 3:
#   ./join-cluster.sh 3 localhost:8081

set -e

NODE_ID=${1:-2}
SEED_ADDR=${2:-"localhost:8081"}

# Calculate ports based on node ID
# Node 1: mysql=3307, grpc=8081
# Node 2: mysql=3308, grpc=8082
# etc.
MYSQL_PORT=$((3306 + NODE_ID))
GRPC_PORT=$((8080 + NODE_ID))

# Directories
DATA_DIR="/tmp/marmot-node-${NODE_ID}"
CONFIG_FILE="/tmp/marmot-node-${NODE_ID}.toml"

echo "=== Marmot Cluster Join ==="
echo "Node ID:     ${NODE_ID}"
echo "Seed:        ${SEED_ADDR}"
echo "MySQL Port:  ${MYSQL_PORT}"
echo "gRPC Port:   ${GRPC_PORT}"
echo "Data Dir:    ${DATA_DIR}"
echo "Config:      ${CONFIG_FILE}"
echo ""

# Kill any existing processes on our ports
echo "Stopping any existing processes on ports ${MYSQL_PORT}, ${GRPC_PORT}..."
lsof -ti:${MYSQL_PORT} -ti:${GRPC_PORT} 2>/dev/null | xargs kill 2>/dev/null || true
sleep 1

# Clean up previous data
echo "Cleaning up previous data directory..."
rm -rf "${DATA_DIR}"

mkdir -p "${DATA_DIR}"

# Generate config file
cat > "${CONFIG_FILE}" << EOF
# Marmot Node ${NODE_ID} Configuration
# Auto-generated by join-cluster.sh

node_id = ${NODE_ID}
data_dir = "${DATA_DIR}"

[cluster]
grpc_bind_address = "0.0.0.0"
grpc_port = ${GRPC_PORT}
grpc_advertise_address = "localhost:${GRPC_PORT}"
seed_nodes = ["${SEED_ADDR}"]
gossip_interval_ms = 1000
gossip_fanout = 3
suspect_timeout_ms = 5000
dead_timeout_ms = 15000

[mysql]
enabled = true
bind_address = "0.0.0.0"
port = ${MYSQL_PORT}

[replication]
default_write_consistency = "QUORUM"  # Replicate to majority
default_read_consistency = "LOCAL_ONE"
write_timeout_ms = 5000
read_timeout_ms = 2000

# Anti-Entropy: Background healing for eventual consistency
enable_anti_entropy = true
anti_entropy_interval_seconds = 30      # Run anti-entropy every 30 seconds
gc_interval_seconds = 60                # GC interval (MUST be >= anti_entropy_interval)
delta_sync_threshold_transactions = 10000  # Use delta sync if lag < 10K txns
delta_sync_threshold_seconds = 3600     # Use snapshot if lag > 1 hour

# Garbage Collection: Reclaim disk space by deleting old transaction records
gc_min_retention_hours = 2   # Minimum 2 hours (must be >= delta threshold)
gc_max_retention_hours = 24  # Force delete after 24 hours

[transaction]
heartbeat_timeout_seconds = 10   # Timeout for transaction heartbeats
conflict_window_seconds = 10     # Window for LWW conflict resolution

[logging]
verbose = true
format = "console"

[prometheus]
enabled = true
EOF

echo "Generated config:"
echo "---"
cat "${CONFIG_FILE}"
echo "---"
echo ""

# Find or build marmot-v2 binary
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [ -f "$REPO_ROOT/marmot-v2" ]; then
    MARMOT_BIN="$REPO_ROOT/marmot-v2"
else
    echo "Building marmot-v2..."
    cd "$REPO_ROOT"
    go build -tags sqlite_preupdate_hook -o marmot-v2 .
    MARMOT_BIN="$REPO_ROOT/marmot-v2"
    echo "✓ Build complete"
fi

echo "Starting Marmot node ${NODE_ID}..."
echo "Connect with: mysql -h localhost -P ${MYSQL_PORT} -u root"
echo ""

exec ${MARMOT_BIN} --config "${CONFIG_FILE}"
