#!/bin/bash
# Marmot v2.0 - Read-Only Replica with Transparent Failover
# Streams from cluster nodes with automatic failover

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Defaults
REPLICA_ID=${1:-1}
FOLLOW_ADDRS=${2:-"localhost:8081,localhost:8082,localhost:8083"}

# Calculate ports based on replica ID
# Replica 1: mysql=3317, grpc=8091
# Replica 2: mysql=3318, grpc=8092
MYSQL_PORT=$((3316 + REPLICA_ID))
GRPC_PORT=$((8090 + REPLICA_ID))

# Directories
DATA_DIR="/tmp/marmot-replica-${REPLICA_ID}"
CONFIG_FILE="/tmp/marmot-replica-${REPLICA_ID}.toml"
LOG_FILE="/tmp/marmot-replica-${REPLICA_ID}/marmot.log"

# Generate random PSK if not provided
generate_secret() {
    openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | xxd -p | head -c 32
}

REPLICA_SECRET=${3:-${MARMOT_REPLICA_SECRET:-$(generate_secret)}}

echo "=== Marmot v2.0 Read-Only Replica ==="
echo "Replica with transparent failover to cluster nodes"
echo ""

# Kill any existing replica processes on our ports
echo "Stopping any existing processes..."
lsof -ti:${MYSQL_PORT} 2>/dev/null | xargs kill 2>/dev/null || true
lsof -ti:${GRPC_PORT} 2>/dev/null | xargs kill 2>/dev/null || true
pkill -f "marmot-replica-${REPLICA_ID}" 2>/dev/null || true
sleep 1

# Clean up old data
echo "Cleaning up old data..."
rm -rf "${DATA_DIR}"
mkdir -p "${DATA_DIR}"

# Build
echo "Building new bits..."
cd "$REPO_ROOT"
go build -tags sqlite_preupdate_hook -o marmot-v2 .

echo "=========================="

# Convert comma-separated addresses to TOML array format
FOLLOW_ADDRS_TOML=$(echo "${FOLLOW_ADDRS}" | sed 's/,/", "/g' | sed 's/^/["/' | sed 's/$/"]/')

# Generate config file
cat > "${CONFIG_FILE}" << EOF
# Marmot Read-Only Replica ${REPLICA_ID} Configuration
# Auto-generated by start-replica.sh

node_id = ${REPLICA_ID}00
data_dir = "${DATA_DIR}"

[cluster]
grpc_bind_address = "0.0.0.0"
grpc_port = ${GRPC_PORT}
grpc_advertise_address = "localhost:${GRPC_PORT}"

[mysql]
enabled = true
bind_address = "0.0.0.0"
port = ${MYSQL_PORT}

[replica]
enabled = true
follow_addresses = ${FOLLOW_ADDRS_TOML}
secret = "${REPLICA_SECRET}"
discovery_interval_seconds = 30
failover_timeout_seconds = 60
reconnect_interval_seconds = 5
reconnect_max_backoff_seconds = 30
initial_sync_timeout_minutes = 30

[metastore]
cache_size_mb = 64
memtable_size_mb = 64

[logging]
verbose = true
format = "console"
EOF

# Cleanup function
cleanup() {
    echo ""
    echo "Shutting down replica..."
    kill "$replica_pid" 2>/dev/null || true
    wait 2>/dev/null || true
    echo "Replica stopped"
}
trap cleanup EXIT

echo ""
echo "Configuration:"
echo "  Replica ID:       ${REPLICA_ID}"
echo "  Follow Addresses: ${FOLLOW_ADDRS}"
echo "  MySQL Port:       ${MYSQL_PORT}"
echo "  gRPC Port:        ${GRPC_PORT}"
echo "  Data Dir:         ${DATA_DIR}"
echo "  PSK Secret:       ${REPLICA_SECRET:0:8}..."
echo ""

# Start replica
"$REPO_ROOT/marmot-v2" --config "${CONFIG_FILE}" > "${LOG_FILE}" 2>&1 &
replica_pid=$!
echo "Replica started (PID: $replica_pid)"

sleep 2

echo ""
echo "=== Replica Running ==="
echo ""
echo "Connect via MySQL protocol:"
echo "  mysql -h 127.0.0.1 -P ${MYSQL_PORT} -u root"
echo ""
echo "NOTE: This is a READ-ONLY replica. Writes will be rejected."
echo "      The replica will automatically failover if disconnected."
echo ""
echo "Logs:"
echo "  tail -f ${LOG_FILE}"
echo ""
echo "PSK Secret (use this in cluster config):"
echo "  ${REPLICA_SECRET}"
echo ""
echo "Press Ctrl+C to stop the replica"
echo "================================"
echo ""

# Wait for replica
wait $replica_pid
