#!/bin/bash
#
# Start a Marmot seed node (node 1)
#
# Usage: ./start-seed.sh
#
# This starts node 1 as the seed node. Other nodes can join using:
#   ./join-cluster.sh 2 localhost:8081
#   ./join-cluster.sh 3 localhost:8081

set -e

NODE_ID=1
MYSQL_PORT=3307
GRPC_PORT=8081

DATA_DIR="/tmp/marmot-node-${NODE_ID}"
CONFIG_FILE="/tmp/marmot-node-${NODE_ID}.toml"

echo "=== Marmot Seed Node ==="
echo "Node ID:     ${NODE_ID}"
echo "MySQL Port:  ${MYSQL_PORT}"
echo "gRPC Port:   ${GRPC_PORT}"
echo "Data Dir:    ${DATA_DIR}"
echo ""

# Clean up previous data (optional)
if [ -d "${DATA_DIR}" ]; then
    echo "Cleaning up previous data directory..."
    rm -rf "${DATA_DIR}"
fi

mkdir -p "${DATA_DIR}"

# Generate config file
cat > "${CONFIG_FILE}" << EOF
# Marmot Seed Node Configuration
# Auto-generated by start-seed.sh

data_dir = "${DATA_DIR}"

[cluster]
grpc_bind_address = "0.0.0.0"
grpc_port = ${GRPC_PORT}
seed_nodes = []  # Empty - this is the seed node
gossip_interval_ms = 1000
gossip_fanout = 3
suspect_timeout_ms = 5000
dead_timeout_ms = 15000

[mysql]
enabled = true
bind_address = "0.0.0.0"
port = ${MYSQL_PORT}

[replication]
write_timeout_ms = 5000
read_timeout_ms = 2000

[logging]
verbose = true
format = "console"
EOF

# Find marmot binary
MARMOT_BIN=""
if [ -f "./marmot-v2" ]; then
    MARMOT_BIN="./marmot-v2"
elif [ -f "./marmot" ]; then
    MARMOT_BIN="./marmot"
elif [ -f "../marmot-v2" ]; then
    MARMOT_BIN="../marmot-v2"
elif [ -f "../marmot" ]; then
    MARMOT_BIN="../marmot"
else
    echo "Building marmot..."
    cd "$(dirname "$0")/.."
    go build -o marmot-v2 .
    MARMOT_BIN="./marmot-v2"
fi

echo "Starting seed node..."
echo "Connect with: mysql -h localhost -P ${MYSQL_PORT} -u root"
echo ""
echo "To add more nodes:"
echo "  ./join-cluster.sh 2 localhost:${GRPC_PORT}"
echo "  ./join-cluster.sh 3 localhost:${GRPC_PORT}"
echo ""

exec ${MARMOT_BIN} --config "${CONFIG_FILE}"
